name: Compilar Presentacion

on:
  push:
    paths:
      - 'presentacion/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/asoleal/tesis-bsf-base:latest

    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Compilar Presentacion
        run: make presentacion

      - name: Subir PDF de la Presentacion
        uses: actions/upload-artifact@v4
        with:
          name: presentacion-pdf
          # Apuntamos específicamente al archivo que genera tu Makefile
          path: presentacion/presentacion.pdf
          retention-days: 5