name: Compilar Tesis

on:
  push:
    paths:
      - 'tesis/**'       
      - 'Makefile'       
  workflow_dispatch:     

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/asoleal/tesis-bsf-base:latest

    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Compilar Tesis
        run: make tesis

      - name: Subir PDF de la Tesis
        uses: actions/upload-artifact@v4
        with:
          name: tesis-pdf
          path: tesis/tesis.pdf # Apuntamos directamente al archivo generado
          retention-days: 5